# Generated by Django 5.0.3 on 2024-03-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('records', '0002_remove_record_id_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
    ]
