# Generated by Django 5.0.3 on 2024-05-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='records',
        ),
    ]
