# Generated by Django 5.0.3 on 2024-05-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_records'),
        ('records', '0027_remove_record_visible_alter_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
    ]
