# Generated by Django 5.0.3 on 2024-05-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='records',
        ),
    ]
