# Generated by Django 5.0.3 on 2024-03-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id_employee',
        ),
    ]
