# Generated by Django 5.0.3 on 2024-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_created_at_record_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='second_name',
        ),
        migrations.AddField(
            model_name='record',
            name='fullname',
            field=models.CharField(default='fio', max_length=256),
            preserve_default=False,
        ),
    ]
