# Generated by Django 5.0.3 on 2024-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_record_first_name_remove_record_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
