# Generated by Django 5.0.3 on 2024-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_record_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='localisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
