# Generated by Django 5.0.3 on 2024-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_record_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='localisation',
            field=models.TextField(blank=True, choices=[('koj', 'кожа'), ('leg', 'легкие (ТАБ)'), ('lim', 'лимфоузлы'), ('mol', 'молочная железа'), ('mya', 'мягкие ткани'), ('moc', 'моча'), ('pod', 'поджелудочная железа (ЭУС)'), ('gin', 'гинекология (шейка матки)'), ('shi', 'щитовидная железа'), ('zhi', 'жидкости')], null=True),
        ),
    ]
