# Generated by Django 5.0.3 on 2024-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_record_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='localisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
