# Generated by Django 5.0.3 on 2024-05-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_record_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.image'),
        ),
        migrations.AlterField(
            model_name='record',
            name='localisation',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
