# Generated by Django 5.0.3 on 2024-05-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_remove_image_record_record_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='records.record'),
            preserve_default=False,
        ),
    ]
