# Generated by Django 5.0.3 on 2024-05-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_record_images_image_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.image'),
        ),
        migrations.AlterField(
            model_name='record',
            name='localisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
