# Generated by Django 5.0.3 on 2024-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_remove_record_image_image_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
