# Generated by Django 5.0.3 on 2024-05-25 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_record_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
