# Generated by Django 5.0.3 on 2024-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
