# Generated by Django 5.0.3 on 2024-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='visible',
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
