# Generated by Django 5.0.3 on 2024-05-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_remove_record_visible_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
    ]
