# Generated by Django 5.0.3 on 2024-05-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_image_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
    ]
