# Generated by Django 5.0.3 on 2024-05-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_remove_image_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='records.record'),
            preserve_default=False,
        ),
    ]
